# Generated by Django 5.2.4 on 2025-07-16 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meilleurecopro', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estate',
            old_name='city',
            new_name='ADS_URL',
        ),
        migrations.RenameField(
            model_name='estate',
            old_name='dept_code',
            new_name='CITY',
        ),
        migrations.RenameField(
            model_name='estate',
            old_name='estate_url',
            new_name='DEPT_CODE',
        ),
        migrations.RenameField(
            model_name='estate',
            old_name='zip_code',
            new_name='ZIP_CODE',
        ),
        migrations.RemoveField(
            model_name='estate',
            name='condominium_expenses',
        ),
        migrations.AddField(
            model_name='estate',
            name='CONDOMINIUM_EXPENSES',
            field=models.FloatField(default=None),
        ),
    ]
