# Generated by Django 5.2.4 on 2025-07-16 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meilleurecopro', '0002_rename_city_estate_ads_url_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estate',
            old_name='ADS_URL',
            new_name='ads_url',
        ),
        migrations.RenameField(
            model_name='estate',
            old_name='CITY',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='estate',
            old_name='CONDOMINIUM_EXPENSES',
            new_name='condominium_expenses',
        ),
        migrations.RenameField(
            model_name='estate',
            old_name='DEPT_CODE',
            new_name='dept_code',
        ),
        migrations.RenameField(
            model_name='estate',
            old_name='ZIP_CODE',
            new_name='zip_code',
        ),
    ]
