# Generated by Django 5.2.4 on 2025-07-16 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meilleurecopro', '0003_rename_ads_url_estate_ads_url_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estate',
            old_name='ads_url',
            new_name='ad_url',
        ),
    ]
