# Generated by Django 5.2.4 on 2025-07-16 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meilleurecopro', '0004_rename_ads_url_estate_ad_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estate',
            name='condominium_expenses',
            field=models.FloatField(default=0),
        ),
    ]
